# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dread < Formula
  desc "Terminal webhook notifications"
  homepage "https://github.com/nigel-engel/dread.sh"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.4.1/dread_darwin_amd64.tar.gz"
      sha256 "fc35905851007820aff897c2f40b8fb6d11c6a240160a756d6a1311d2634f7ce"

      define_method(:install) do
        bin.install "dread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.4.1/dread_darwin_arm64.tar.gz"
      sha256 "5c84414f183aa15a3456e1d191e5c35e516fa6ddfa6df807fccde29b8503ee81"

      define_method(:install) do
        bin.install "dread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.4.1/dread_linux_amd64.tar.gz"
      sha256 "665646381cc035c1cf227333bb18a5468cc83529e39d5048e6a6d56749ac948c"
      define_method(:install) do
        bin.install "dread"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.4.1/dread_linux_arm64.tar.gz"
      sha256 "c33fe8c902e4c5891c11244115e136fb63003158617cbd6e1b49321f2d829012"
      define_method(:install) do
        bin.install "dread"
      end
    end
  end
end
