# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dread < Formula
  desc "Terminal webhook notifications"
  homepage "https://github.com/nigel-engel/dread.sh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.1.0/dread_darwin_amd64.tar.gz"
      sha256 "e25b58260a1b4d8cce78b24a9853148754717105e488fb0314613286e3edb68c"

      define_method(:install) do
        bin.install "dread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.1.0/dread_darwin_arm64.tar.gz"
      sha256 "56aee579f83509beee54e99bb67d458145830d395ea3386135e6d40e5dc218f3"

      define_method(:install) do
        bin.install "dread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.1.0/dread_linux_amd64.tar.gz"
      sha256 "26ef88f80b12a0c855541e261909a98116a97629f449038dd6befc9d709f1be6"
      define_method(:install) do
        bin.install "dread"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nigel-engel/dread.sh/releases/download/v0.1.0/dread_linux_arm64.tar.gz"
      sha256 "3709126e9c1d344f4732e47133aa77a5d81e7fbad155b8537d4da085d25239f1"
      define_method(:install) do
        bin.install "dread"
      end
    end
  end
end
